### PR TITLE
Update to sphinx theme master 1.3.0

### PR DESCRIPTION
**Pull request by khancyr**
Squashed commit to 1.3.0

### CODE REVIEW

**Comment by khancyr** [comment]
image
small diff

**Comment by Hwurzburg** [comment]
> image small diff

sorry dont understand what you are trying to show

**Comment by khancyr** [comment]
that show a diff between the current version on left and the new version on right. 
we need to look at right of the house icon : previously is was >> now it is / .

**Comment by Hwurzburg** [comment]
thats not significant, will merge if you think its safe

**Comment by khancyr** [comment]
@Hwurzburg seems pretty safe. If we found some glitch or things we dislike, I can easily fix them tomorrow. But I didn't spot any difference other than this one.

**Comment by Hwurzburg** [comment]
okay...merging

**Pull request merged**
