### PR TITLE
Theme update

### PR DESCRIPTION
**Pull request by khancyr**
Do a major upgrade of the theme. This will surely need a force push on master branch as rebase was a pain...
Update to the latest release
Disable npm dependencies as they aren't needed.
Squash our change in a single commit for easier management
Split our css change into a new ardupilot.css file.
Remove swag shop links

What does it solve : 
numerous fix in JS, css and performances

Release process : 
backup current master branch, force push this branch on master. Then the wiki need to reinstall the theme with pip

### CODE REVIEW

**Comment by rmackay9** [comment]
It's too bad that this includes all these "merge" commits but this is a problem with upstream so we can't do anything about it.

I guess if we take a backup of what we have (perhaps add a tag) and the force push we will be able to get back if we want to.

**Comment by tridge** [comment]
@Hwurzburg I can help with install of this for you to test if you have issues with it (I should still have ssh access)

**Comment by khancyr** [comment]
The simplest to use this is to modify the `Sphinxsetup.sh` script by changing 
`python3 -m pip install git+https://github.com/ArduPilot/sphinx_rtd_theme.git --upgrade`
to 
`python3 -m pip install git+https://github.com/khancyr/sphinx_rtd_theme.git@new2 --upgrade`

It will then update the theme with this update. And then you can build the wiki as previously !

**Comment by khancyr** [comment]
python3 -m pip install git+https://github.com/khancyr/sphinx_rtd_theme.git@new2 --upgrade

It will then update the theme with this update. And then you can build the wiki as previously !

**Comment by khancyr** [comment]
@tridge @Hwurzburg when is the next wiki meeting? I want to get this in !

**Comment by Hwurzburg** [comment]
we don't have regular wiki meetings, but can have one whenever you guys are available.....I am anytime that I am awake (7AM to 10PM CentralStandTime).I have no idea how to test this and it has lots of conflicts at the moment...

**Comment by TunaLobster** [comment]
6 month bump on this one. Would be nice to get this merged.

**Comment by khancyr** [comment]
I need to redo it as we have push some change in the same time... but yes that would be great to have it

**Comment by TunaLobster** [comment]
Which version of the theme is this updating to? It will mater for rendering bullet points on the wiki. See https://stackoverflow.com/a/68685753/2578171

**Comment by khancyr** [comment]
It was updating to version 1.0 something.
I will try to redo it this week and we can plan a meeting with Henry to get this merged

**Comment by khancyr** [comment]
double checked we are update to date !  we just need to pass this as main branch.

**Pull request merged**
