### PR TITLE
Add support for more compact table presentation

### PR DESCRIPTION
**Pull request by hamishwillee**
This adds (slightly modified) changes from https://github.com/ArduPilot/ardupilot_wiki/pull/537 to theme (via @tomlauzon)

### CODE REVIEW

**Comment by hamishwillee** [comment]
This adds changes to the theme. @tomlauzon and @magicrub - sanity check?

**Comment by magicrub** [comment]
.. how do  i check this?

**Comment by hamishwillee** [comment]
@magicrub YOu'd have to get my branch, and follow the instructions in the readme to build it https://github.com/ArduPilot/sphinx_rtd_theme#set-up-your-environment

Perhaps better if you just inspect the output below (for new theme) and  [compare to the old version here](http://ardupilot.org/copter/docs/common-telemetry-radio-regional-regulations.html#support-for-different-countries-regions). The new version breaks on whitespace in both headings and text, so is much more compact. 
I made this change such that it occurs irrespective of screen size.

image

**Comment by tomlauzon** [comment]
@hamishwillee I tested your modifications and it works quite well. The telemetry regulations pages given as an example still has a scroll bar but manageable. I also tried it with the FrSky telemetry page I'm working on and the tables look great and have no scroll bars underneath them. 
I see common-mavlink-mission-command-messages-mav_cmd.html is also greatly improved thanks to your fix. 

I'm not sure how to test on mobile. From what I read, the point of scrolling in the original version of the theme was to enable swiping for large tables. I tried zooming in to simulate mobile and the scroll bars reappear as they should. So, I would think the tables will display well on tablets/phones.

Looks good to me!

@magicrub for testing you could place the contents of this attached zip file in your copter/source folder. It's the branch from the pull request and a modified conf.py to use the proposed theme. Make sure to replace conf.py by the one in the zip and then launch "python update.py" from the base folder, as usual. Obviously not the way to install the theme properly but it's an easy way to test it.

[sphinx_theme.zip](https://github.com/ArduPilot/sphinx_rtd_theme/files/499102/sphinx_theme.zip)

**Comment by hamishwillee** [comment]
Hi @magicrub @tomlauzon 

I'm happy with this. Self merging :-)

**Comment by tomlauzon** [comment]
Great job!

**Pull request merged**
